language: node_js
node_js:
  - '10'
  - '12'
  - '14'
cache: yarn
after_success:
  - yarn run build:docs
deploy:
  - provider: npm
    edge: true
    api_token: $NPM_TOKEN
    email: 'luongquangmanh85@gmail.com'
    on:
      branch: master
      tags: true
    cleanup: false
  - provider: releases
    edge: true
    token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
    cleanup: false
  - provider: pages
    edge: true
    token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
      tags: true
    cleanup: false
